"""remove_max_queries_per_day_from_query_users

Revision ID: 1d60b64d31cc
Revises: 20260115_add_file_is_public
Create Date: 2026-01-16 17:09:03.125109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d60b64d31cc'
down_revision: Union[str, Sequence[str], None] = '20260115_add_file_is_public'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='建立時間',
               existing_nullable=False)
    op.alter_column('file_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='更新時間',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_file_permissions_user_file'), 'file_permissions', type_='unique')
    op.alter_column('query_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='建立時間',
               existing_nullable=False)
    op.alter_column('query_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='更新時間',
               existing_nullable=False)
    op.drop_table_comment(
        'query_users',
        existing_comment='查詢用戶表（用於前端查詢系統）',
        schema=None
    )
    op.drop_column('query_users', 'max_queries_per_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_users', sa.Column('max_queries_per_day', sa.INTEGER(), autoincrement=False, nullable=True, comment='每日查詢次數限制（NULL 表示不限制）'))
    op.create_table_comment(
        'query_users',
        '查詢用戶表（用於前端查詢系統）',
        existing_comment=None,
        schema=None
    )
    op.alter_column('query_users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新時間',
               existing_nullable=False)
    op.alter_column('query_users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='建立時間',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_file_permissions_user_file'), 'file_permissions', ['query_user_id', 'file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('file_permissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新時間',
               existing_nullable=False)
    op.alter_column('file_permissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='建立時間',
               existing_nullable=False)
    # ### end Alembic commands ###
